---
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - name: commitlint
        id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - '@commitlint/config-conventional'
        description: >-
          Ensure commit messages follow Conventional Commit spec
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - name: gitlint
        id: gitlint
        description: >-
          Lint git commit messages.
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - name: sign-commit
        id: sign-commit
        language_version: 3.1.0
        stages:
          - commit-msg
        description: >-
          Ensure commit messages are signed
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
      - name: gitleaks
        id: gitleaks
        description: >-
          Detect hardcoded secrets using Gitleaks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks: []
