---
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - name: commitlint
        id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - '@commitlint/config-conventional'
        description: >-
          Ensure commit messages follow Conventional Commit spec
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - name: gitlint
        id: gitlint
        description: >-
          Lint git commit messages.
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - name: sign-commit
        id: sign-commit
        language_version: 3.1.0
        stages:
          - commit-msg
        description: >-
          Ensure commit messages are signed
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
      - name: gitleaks
        id: gitleaks
        description: >-
          Detect hardcoded secrets using Gitleaks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - name: forbid-crlf
        id: forbid-crlf
        description: >-
          forbid CRLF (carriage return) line endings (added in
          Windows by default)
      - name: remove-crlf
        id: remove-crlf
        description: >-
          remove CRLF (carriage return) line endings (added in
          Windows by default)
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
      - name: editorconfig-checker
        id: editorconfig-checker
        exclude: CHANGELOG.md
        description: >-
          Ensure files are consistent with .editorconfig
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - name: markdownlint-fix
        id: markdownlint-fix
        description: >-
          automatically fix markdown errors.
      - name: markdownlint
        id: markdownlint
        args:
          - -c
          - .markdownlint.yaml
        description: >-
          Lint markdown Documents
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - name: shfmt
        id: shfmt
        description: >-
          Check shell style with shfmt
      - name: shellcheck
        id: shellcheck
        description: >-
          Shell scripts conform to shellcheck
  - repo: https://github.com/google/yamlfmt
    rev: v0.9.0
    hooks:
      - name: yamlfmt
        id: yamlfmt
        exclude: .*docker-compose.*
        args:
          - -conf
          - .yamlfmt
        description: >-
          Ensure YAML files are formatted
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.31.0
    hooks:
      - id: yamllint
        name: yamllint
        exclude: .*docker-compose.*|Taskfile.*.yaml
        args:
          - --format
          - parsable
          - --strict
        description: >-
          Ensure YAML files are valid
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
        name: docker-compose-check
        description: >-
          ensure validity of docker-compose files
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
        name: hadolint-docker
        entry: hadolint/hadolint hadolint
        description: >-
          Lint Dockerfiles with hadolint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        name: prettier-markdown
        alias: prettier-markdown
        args:
          - --print-width=79
          - --prose-wrap=always
          - --parser=markdown
        files: \.(md|mdown|markdown)$
        description: >-
          Fix some markdown formatting issues with Prettier
  - repo: https://github.com/returntocorp/semgrep
    rev: "v1.20.0"
    hooks:
      - id: semgrep
        name: semgrep-docker
        alias: semgrep-docker
        args:
          - --config=auto
        description: >-
          Run checks against Terraform Dockerfiles with Semgrep
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: check-added-large-files
        args:
          - --maxkb=1024
        description: >-
          prevents giant files from being committed.
      - id: mixed-line-ending
        name: mixed-line-ending
        args:
          - --fix=lf
        description: >-
          replaces or checks mixed line ending.
      - id: trailing-whitespace
        name: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        description: >-
          trims trailing whitespace.
      - id: detect-private-key
        name: detect-private-key
        exclude: .gitleaks.toml
        description: >-
          detects the presence of private keys.
      - id: check-merge-conflict
        name: check-merge-conflict
        description: >-
          checks for files that contain merge conflict strings.
      - id: fix-byte-order-marker
        name: fix-byte-order-marker
        description: >-
          removes utf-8 byte order marker.
      - id: check-case-conflict
        name: check-case-conflict
        description: >-
          checks for files that would conflict in case-insensitive
          filesystems.
      - id: check-executables-have-shebangs
        name: check-executables-have-shebangs
        description: >-
          ensures that (non-binary) executables have a shebang.
      - id: check-shebang-scripts-are-executable
        name: check-shebang-scripts-are-executable
        description: >-
          ensures that (non-binary) files with a shebang are executable
      - id: check-symlinks
        name: check-symlinks
        description: >-
          checks for symlinks which do not point to anything.
      - id: destroyed-symlinks
        name: destroyed-symlinks
        description: >-
          detects symlinks which are changed to regular files
          with a content of a path which that symlink was pointing
          to.
      - id: end-of-file-fixer
        name: end-of-file-fixer
        description: >-
          ensures that a file is either empty, or ends with one
          newline.
