---
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - name: commitlint
        id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - '@commitlint/config-conventional'
        description: >-
          Ensure commit messages follow Conventional Commit spec
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks: []
