---
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - name: commitlint
        id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - '@commitlint/config-conventional'
        description: >-
          Ensure commit messages follow Conventional Commit spec
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - name: gitlint
        id: gitlint
        description: >-
          Lint git commit messages.
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - name: sign-commit
        id: sign-commit
        language_version: 3.1.0
        stages:
          - commit-msg
        description: >-
          Ensure commit messages are signed
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
      - name: gitleaks
        id: gitleaks
        description: >-
          Detect hardcoded secrets using Gitleaks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - name: forbid-crlf
        id: forbid-crlf
        description: >-
          forbid CRLF (carriage return) line endings (added in
          Windows by default)
      - name: remove-crlf
        id: remove-crlf
        description: >-
          remove CRLF (carriage return) line endings (added in
          Windows by default)
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
      - name: editorconfig-checker
        id: editorconfig-checker
        exclude: CHANGELOG.md
        description: >-
          Ensure files are consistent with .editorconfig
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - name: markdownlint-fix
        id: markdownlint-fix
        description: >-
          automatically fix markdown errors.
      - name: markdownlint
        id: markdownlint
        args:
          - -c
          - .markdownlint.yaml
        description: >-
          Lint markdown Documents
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks: []
