---
version: "3"
tasks:
  clear-images:
    aliases: [clean-images, ci]
    cmds:
      - cmd: docker rmi -f $(docker images -aq) ;
    preconditions:
      - sh: docker --version
        msg: "`docker` was not found in PATH"
  clear-containers:
    aliases: [clean-containers]
    cmds:
      - cmd: docker rm -f $(docker ps -aq) ;
    preconditions:
      - sh: docker --version
        msg: "`docker` was not found in PATH"
  prune-cache:
    aliases: [prune, clean-cache, cc]
    cmds:
      - cmd: docker builder prune --all --force ;
    preconditions:
      - sh: docker --version
        msg: "`docker` was not found in PATH"
      - sh: docker buildx version
        msg: "`docker buildx` was not found in PATH"
  # TODO: add powershell support
  switch-default-builder-context:
    internal: true
    aliases: [clean-builders, prune-builders, cb]
    cmds:
      - cmd: docker buildx use default ;
      - cmd: docker buildx stop $(basename -s.git "$(git remote
          get-url origin)") ;
        platforms: [linux, darwin]
    preconditions:
      - sh: git --version
        msg: "`git` was not found in PATH"
      - sh: docker --version
        msg: "`docker` was not found in PATH"
      - sh: docker buildx version
        msg: "`docker buildx` was not found in PATH"
  clear-builders:
    aliases: [clean-builders, prune-builders, cb]
    cmds:
      - cmd: docker buildx rm --all-inactive --force ;
    preconditions:
      - sh: docker --version
        msg: "`docker` was not found in PATH"
      - sh: docker buildx version
        msg: "`docker buildx` was not found in PATH"
