---
version: "3"
tasks:
  install:
    aliases: [pre-commit-init, init]
    cmds:
      - cmd: pre-commit install ;
      - cmd: pre-commit install --install-hooks ;
      - cmd: pre-commit install --hook-type pre-commit  ;
      - cmd: pre-commit install --hook-type commit-msg  ;
    status:
      - "[ -r .git/hooks/pre-commit ] && exit 0 || exit 1"
    preconditions:
      - sh: python3 --version
        msg: "`python3` was not found in PATH"
      - sh: pre-commit --version
        msg: "`pre-commit` was not found in PATH\n\nInstall it
          through your OS package manager or by running:\n  \n
          \ python3 -m pip install pre-commit\n"
