---
name: "shisho"
# yamllint disable-line rule:truthy
on:
  # push:
  workflow_dispatch:
jobs:
  shisho-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        id: checkout-head
        uses: actions/checkout@v3
      - name: Run Shisho
        id: run-shisho
        uses: flatt-security/shisho-action@main
        with:
          ruleset-path: "./shisho"
